var colorCodeTableDataHelper = {
    GetColorCodeTable: function () {
        return [{
            id: 0,
            name: "Black",
            codeName: "Bl",
            value: 0,
            multiplier: 1,
            tolerence: 0
        }, {
            id: 1,
            name: "Brown",
            codeName: "Br",
            value: 1,
            multiplier: 10,
            tolerence: 1
        }, {
            id: 2,
            name: "Red",
            codeName: "R",
            value: 2,
            multiplier: 100,
            tolerence: 2
        }, {
            id: 3,
            name: "Orange",
            codeName: "O",
            value: 3,
            multiplier: 1000,
            tolerence: 0
        }, {
            id: 4,
            name: "Yellow",
            codeName: "Y",
            value: 4,
            multiplier: 10000,
            tolerence: 0
        }, {
            id: 5,
            name: "Green",
            codeName: "G",
            value: 5,
            multiplier: 100000,
            tolerence: 0.5
        }, {
            id: 6,
            name: "Blue",
            codeName: "Blu",
            value: 6,
            multiplier: 1000000,
            tolerence: 0.25
        }, {
            id: 7,
            name: "Violet",
            codeName: "V",
            value: 7,
            multiplier: 10000000,
            tolerence: 0.10
        }, {
            id: 8,
            name: "Grey",
            codeName: "Gr",
            value: 8,
            multiplier: 100000000,
            tolerence: 0.05
        }, {
            id: 9,
            name: "White",
            codeName: "W",
            value: 9,
            multiplier: 1000000000,
            tolerence: 0
        }, {
            id: 10,
            name: "Gold",
            codeName: "Gd",
            value: 0,
            multiplier: 0.1,
            tolerence: 5
        }, {
            id: 11,
            name: "Silver",
            codeName: "S",
            value: 0,
            multiplier: 0.01,
            tolerence: 10
        }];
    }
}

module.exports = colorCodeTableDataHelper;
